name: Create Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    env:
        NODE_VERSION: '22'
        NODE_OPTIONS:  "--max_old_space_size=4096"
  
    permissions:
      id-token: write
      
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '22.x'
          registry-url: https://registry.npmjs.org/

      - name: Install node modules and verify build
        run: npm ci && npm run build-release

      - name: Publish FDC3 Library
        run: cd projects/lib/dist && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Messaging Provider Library
        run: cd projects/messaging-provider/dist && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish UI Provider Library
        run: cd projects/ui-provider/dist && npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
